### PR TITLE
Docker file and read me

### PR DESCRIPTION
**Pull request by Hari-1027**
1. added the docker file to support and CI CD git action 
2. Added content to the Read me file

### CODE REVIEW

**Comment by Hari-1027** [comment]
@HarishGangula 
1. cleared the action error from - https://github.com/Assisted-Math-Learning/aml-api-service/actions/runs/10297378443/job/28500392843
2. added Prerequisites instructions in the read me file
3. enabled git actions for PR also to test the build action.

**Comment by HarishGangula** [comment]
Build and deploy action should happen only on tag creation not for PR

**Comment by Hari-1027** [comment]
> @Hari-1027 Build and deploy action should happen only on tag creation not for PR

Removed the Build and deploy action trigger for a PR. @HarishGangula

**Review by HarishGangula — CHANGES_REQUESTED** [review]
Add the docker ignore file as well

**Comment by Hari-1027** [comment]
@HarishGangula Added docker ignore file and tested the docker in local. 
Kindly confirm Postgresql will be installed in the server sepreratly or we we have to dockerize DB too. 

Screenshot 2024-08-09 at 6 08 46 PM

**Review by HarishGangula — APPROVED** [review]

**Pull request merged**
