### PR TITLE
fix:modified the folder strucuture

### PR DESCRIPTION
**Pull request by vishwab1**
This Repository having plain Structure @HarishGangula

### CODE REVIEW

**Review by HarishGangula — CHANGES_REQUESTED** [review]
Why we have test and types under v1 folder ?

**Comment by vishwab1** [comment]
> Why we have test and types under v1 folder ?
we are followed the obsrv folder structure, so should remove or where should kept?

**Comment by HarishGangula** [comment]
@vishwab1 There should reason for this we have different versions of api completely not backward compatible here, we don't even written v1 so remove that

**Comment by vishwab1** [comment]
@HarishGangula  means not need of V1 folder also not needed now ?

**Comment by HarishGangula** [comment]
Yes remove v1 folder

**Comment by vishwab1** [comment]
@HarishGangula  update the new structure please verify and have doubt here where will test folder then?

**Pull request merged**
